/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.server.module';
import * as import2 from '@angular/http';
import * as import3 from '@angular/common';
import * as import4 from '@angular/router';
import * as import5 from '@angular/platform-browser';
import * as import6 from '@angular/platform-browser/animations';
import * as import7 from '@angular/platform-server';
import * as import8 from '@angular/forms';
import * as import9 from './app-routing.module';
import * as import10 from './app.module';
import * as import11 from '@angular/animations/browser';
import * as import12 from './providers/ftc-database';
import * as import13 from './views/home/home.component.ngfactory';
import * as import14 from './views/events/events.component.ngfactory';
import * as import15 from './views/event/event.component.ngfactory';
import * as import16 from './app.component.ngfactory';
import * as import17 from './views/home/home.component';
import * as import18 from './views/events/events.component';
import * as import19 from './views/event/event.component';
class AppServerModuleInjector extends import0.ɵNgModuleInjector<import1.AppServerModule> {
  _HttpModule_0:import2.HttpModule;
  _CommonModule_1:import3.CommonModule;
  _ErrorHandler_2:any;
  _NgProbeToken_3:any[];
  _ɵg_4:import4.ɵg;
  _APP_ID_5:any;
  _ɵTRANSITION_ID_6:any;
  _APP_INITIALIZER_7:any[];
  _ApplicationInitStatus_8:import0.ApplicationInitStatus;
  _ɵf_9:import0.ɵf;
  _ApplicationRef_10:any;
  _ApplicationModule_11:import0.ApplicationModule;
  _BrowserModule_12:import5.BrowserModule;
  _NoopAnimationsModule_13:import6.NoopAnimationsModule;
  _ServerModule_14:import7.ServerModule;
  _ɵba_15:import8.ɵba;
  _FormsModule_16:import8.FormsModule;
  _ɵa_17:any;
  _UrlSerializer_18:import4.DefaultUrlSerializer;
  _RouterOutletMap_19:import4.RouterOutletMap;
  _ROUTER_CONFIGURATION_20:any;
  _LocationStrategy_21:any;
  _Location_22:import3.Location;
  _Compiler_23:import0.Compiler;
  _NgModuleFactoryLoader_24:import0.SystemJsNgModuleLoader;
  _ROUTES_25:any[];
  _Router_26:any;
  _RouterModule_27:import4.RouterModule;
  _AppRoutingModule_28:import9.AppRoutingModule;
  _AppModule_29:import10.AppModule;
  _AppServerModule_30:import1.AppServerModule;
  __BrowserXhr_31:import7.ɵc;
  __ResponseOptions_32:import2.BaseResponseOptions;
  __XSRFStrategy_33:import7.ɵd;
  __XHRBackend_34:import2.XHRBackend;
  __RequestOptions_35:import2.BaseRequestOptions;
  __Http_36:any;
  __LOCALE_ID_37:any;
  __NgLocalization_38:import3.NgLocaleLocalization;
  __IterableDiffers_39:any;
  __KeyValueDiffers_40:any;
  __DomSanitizer_41:import5.ɵe;
  __Sanitizer_42:any;
  __HAMMER_GESTURE_CONFIG_43:import5.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_44:any[];
  __EventManager_45:import5.EventManager;
  __ɵDomSharedStylesHost_46:import5.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_47:import5.ɵDomRendererFactory2;
  __ɵb_48:import7.ɵb;
  __ɵSharedStylesHost_49:any;
  __ɵServerRendererFactory2_50:import7.ɵServerRendererFactory2;
  __ɵAnimationEngine_51:import11.ɵNoopAnimationEngine;
  __RendererFactory2_52:any;
  __Testability_53:any;
  __Meta_54:import5.Meta;
  __Title_55:import5.Title;
  __ɵi_56:import8.ɵi;
  __ActivatedRoute_57:any;
  __NoPreloading_58:import4.NoPreloading;
  __PreloadingStrategy_59:any;
  __RouterPreloader_60:import4.RouterPreloader;
  __PreloadAllModules_61:import4.PreloadAllModules;
  __ROUTER_INITIALIZER_62:any;
  __APP_BOOTSTRAP_LISTENER_63:any[];
  __FTCDatabase_64:import12.FTCDatabase;
  constructor(parent:import0.Injector) {
    super(parent,[
      import13.HomeComponentNgFactory,
      import14.EventsComponentNgFactory,
      import15.EventComponentNgFactory,
      import16.TheOrangeAllianceComponentNgFactory
    ]
    ,[import16.TheOrangeAllianceComponentNgFactory]);
  }
  get _BrowserXhr_31():import7.ɵc {
    if ((this.__BrowserXhr_31 == null)) { (this.__BrowserXhr_31 = new import7.ɵc()); }
    return this.__BrowserXhr_31;
  }
  get _ResponseOptions_32():import2.BaseResponseOptions {
    if ((this.__ResponseOptions_32 == null)) { (this.__ResponseOptions_32 = new import2.BaseResponseOptions()); }
    return this.__ResponseOptions_32;
  }
  get _XSRFStrategy_33():import7.ɵd {
    if ((this.__XSRFStrategy_33 == null)) { (this.__XSRFStrategy_33 = new import7.ɵd()); }
    return this.__XSRFStrategy_33;
  }
  get _XHRBackend_34():import2.XHRBackend {
    if ((this.__XHRBackend_34 == null)) { (this.__XHRBackend_34 = new import2.XHRBackend(this._BrowserXhr_31,this._ResponseOptions_32,this._XSRFStrategy_33)); }
    return this.__XHRBackend_34;
  }
  get _RequestOptions_35():import2.BaseRequestOptions {
    if ((this.__RequestOptions_35 == null)) { (this.__RequestOptions_35 = new import2.BaseRequestOptions()); }
    return this.__RequestOptions_35;
  }
  get _Http_36():any {
    if ((this.__Http_36 == null)) { (this.__Http_36 = import7.ɵe(this._XHRBackend_34,this._RequestOptions_35)); }
    return this.__Http_36;
  }
  get _LOCALE_ID_37():any {
    if ((this.__LOCALE_ID_37 == null)) { (this.__LOCALE_ID_37 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_37;
  }
  get _NgLocalization_38():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_38 == null)) { (this.__NgLocalization_38 = new import3.NgLocaleLocalization(this._LOCALE_ID_37)); }
    return this.__NgLocalization_38;
  }
  get _IterableDiffers_39():any {
    if ((this.__IterableDiffers_39 == null)) { (this.__IterableDiffers_39 = import0.ɵl()); }
    return this.__IterableDiffers_39;
  }
  get _KeyValueDiffers_40():any {
    if ((this.__KeyValueDiffers_40 == null)) { (this.__KeyValueDiffers_40 = import0.ɵm()); }
    return this.__KeyValueDiffers_40;
  }
  get _DomSanitizer_41():import5.ɵe {
    if ((this.__DomSanitizer_41 == null)) { (this.__DomSanitizer_41 = new import5.ɵe(this.parent.get(import5.DOCUMENT))); }
    return this.__DomSanitizer_41;
  }
  get _Sanitizer_42():any {
    if ((this.__Sanitizer_42 == null)) { (this.__Sanitizer_42 = this._DomSanitizer_41); }
    return this.__Sanitizer_42;
  }
  get _HAMMER_GESTURE_CONFIG_43():import5.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_43 == null)) { (this.__HAMMER_GESTURE_CONFIG_43 = new import5.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_43;
  }
  get _EVENT_MANAGER_PLUGINS_44():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_44 == null)) { (this.__EVENT_MANAGER_PLUGINS_44 = [
      new import5.ɵDomEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵKeyEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵHammerGesturesPlugin(this.parent.get(import5.DOCUMENT),this._HAMMER_GESTURE_CONFIG_43)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_44;
  }
  get _EventManager_45():import5.EventManager {
    if ((this.__EventManager_45 == null)) { (this.__EventManager_45 = new import5.EventManager(this._EVENT_MANAGER_PLUGINS_44,this.parent.get(import0.NgZone))); }
    return this.__EventManager_45;
  }
  get _ɵDomSharedStylesHost_46():import5.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_46 == null)) { (this.__ɵDomSharedStylesHost_46 = new import5.ɵDomSharedStylesHost(this.parent.get(import5.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_46;
  }
  get _ɵDomRendererFactory2_47():import5.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_47 == null)) { (this.__ɵDomRendererFactory2_47 = new import5.ɵDomRendererFactory2(this._EventManager_45,this._ɵDomSharedStylesHost_46)); }
    return this.__ɵDomRendererFactory2_47;
  }
  get _ɵb_48():import7.ɵb {
    if ((this.__ɵb_48 == null)) { (this.__ɵb_48 = new import7.ɵb(this.parent.get(import5.DOCUMENT),this._ɵTRANSITION_ID_6)); }
    return this.__ɵb_48;
  }
  get _ɵSharedStylesHost_49():any {
    if ((this.__ɵSharedStylesHost_49 == null)) { (this.__ɵSharedStylesHost_49 = this._ɵb_48); }
    return this.__ɵSharedStylesHost_49;
  }
  get _ɵServerRendererFactory2_50():import7.ɵServerRendererFactory2 {
    if ((this.__ɵServerRendererFactory2_50 == null)) { (this.__ɵServerRendererFactory2_50 = new import7.ɵServerRendererFactory2(this.parent.get(import0.NgZone),this.parent.get(import5.DOCUMENT),this._ɵSharedStylesHost_49)); }
    return this.__ɵServerRendererFactory2_50;
  }
  get _ɵAnimationEngine_51():import11.ɵNoopAnimationEngine {
    if ((this.__ɵAnimationEngine_51 == null)) { (this.__ɵAnimationEngine_51 = new import11.ɵNoopAnimationEngine()); }
    return this.__ɵAnimationEngine_51;
  }
  get _RendererFactory2_52():any {
    if ((this.__RendererFactory2_52 == null)) { (this.__RendererFactory2_52 = import7.ɵa(this._ɵServerRendererFactory2_50,this._ɵAnimationEngine_51,this.parent.get(import0.NgZone))); }
    return this.__RendererFactory2_52;
  }
  get _Testability_53():any {
    if ((this.__Testability_53 == null)) { (this.__Testability_53 = (null as any)); }
    return this.__Testability_53;
  }
  get _Meta_54():import5.Meta {
    if ((this.__Meta_54 == null)) { (this.__Meta_54 = new import5.Meta(this.parent.get(import5.DOCUMENT))); }
    return this.__Meta_54;
  }
  get _Title_55():import5.Title {
    if ((this.__Title_55 == null)) { (this.__Title_55 = new import5.Title(this.parent.get(import5.DOCUMENT))); }
    return this.__Title_55;
  }
  get _ɵi_56():import8.ɵi {
    if ((this.__ɵi_56 == null)) { (this.__ɵi_56 = new import8.ɵi()); }
    return this.__ɵi_56;
  }
  get _ActivatedRoute_57():any {
    if ((this.__ActivatedRoute_57 == null)) { (this.__ActivatedRoute_57 = import4.ɵf(this._Router_26)); }
    return this.__ActivatedRoute_57;
  }
  get _NoPreloading_58():import4.NoPreloading {
    if ((this.__NoPreloading_58 == null)) { (this.__NoPreloading_58 = new import4.NoPreloading()); }
    return this.__NoPreloading_58;
  }
  get _PreloadingStrategy_59():any {
    if ((this.__PreloadingStrategy_59 == null)) { (this.__PreloadingStrategy_59 = this._NoPreloading_58); }
    return this.__PreloadingStrategy_59;
  }
  get _RouterPreloader_60():import4.RouterPreloader {
    if ((this.__RouterPreloader_60 == null)) { (this.__RouterPreloader_60 = new import4.RouterPreloader(this._Router_26,this._NgModuleFactoryLoader_24,this._Compiler_23,this,this._PreloadingStrategy_59)); }
    return this.__RouterPreloader_60;
  }
  get _PreloadAllModules_61():import4.PreloadAllModules {
    if ((this.__PreloadAllModules_61 == null)) { (this.__PreloadAllModules_61 = new import4.PreloadAllModules()); }
    return this.__PreloadAllModules_61;
  }
  get _ROUTER_INITIALIZER_62():any {
    if ((this.__ROUTER_INITIALIZER_62 == null)) { (this.__ROUTER_INITIALIZER_62 = import4.ɵi(this._ɵg_4)); }
    return this.__ROUTER_INITIALIZER_62;
  }
  get _APP_BOOTSTRAP_LISTENER_63():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_63 == null)) { (this.__APP_BOOTSTRAP_LISTENER_63 = [this._ROUTER_INITIALIZER_62]); }
    return this.__APP_BOOTSTRAP_LISTENER_63;
  }
  get _FTCDatabase_64():import12.FTCDatabase {
    if ((this.__FTCDatabase_64 == null)) { (this.__FTCDatabase_64 = new import12.FTCDatabase(this._Http_36)); }
    return this.__FTCDatabase_64;
  }
  createInternal():import1.AppServerModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._CommonModule_1 = new import3.CommonModule();
    this._ErrorHandler_2 = import5.ɵa();
    this._NgProbeToken_3 = [import4.ɵb()];
    this._ɵg_4 = new import4.ɵg(this);
    this._APP_ID_5 = 'the-orange-alliance';
    this._ɵTRANSITION_ID_6 = this._APP_ID_5;
    this._APP_INITIALIZER_7 = [
      import0.ɵo,
      import5.ɵc(this.parent.get(import5.NgProbeToken,(null as any)),this._NgProbeToken_3),
      import4.ɵh(this._ɵg_4),
      import5.ɵf(this._ɵTRANSITION_ID_6,this.parent.get(import5.DOCUMENT),this)
    ]
    ;
    this._ApplicationInitStatus_8 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_7);
    this._ɵf_9 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_2,this.componentFactoryResolver,this._ApplicationInitStatus_8);
    this._ApplicationRef_10 = this._ɵf_9;
    this._ApplicationModule_11 = new import0.ApplicationModule(this._ApplicationRef_10);
    this._BrowserModule_12 = new import5.BrowserModule(this.parent.get(import5.BrowserModule,(null as any)));
    this._NoopAnimationsModule_13 = new import6.NoopAnimationsModule();
    this._ServerModule_14 = new import7.ServerModule();
    this._ɵba_15 = new import8.ɵba();
    this._FormsModule_16 = new import8.FormsModule();
    this._ɵa_17 = import4.ɵd(this.parent.get(import4.Router,(null as any)));
    this._UrlSerializer_18 = new import4.DefaultUrlSerializer();
    this._RouterOutletMap_19 = new import4.RouterOutletMap();
    this._ROUTER_CONFIGURATION_20 = {};
    this._LocationStrategy_21 = import4.ɵc(this.parent.get(import3.PlatformLocation),this.parent.get(import3.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_20);
    this._Location_22 = new import3.Location(this._LocationStrategy_21);
    this._Compiler_23 = new import0.Compiler();
    this._NgModuleFactoryLoader_24 = new import0.SystemJsNgModuleLoader(this._Compiler_23,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_25 = [[
        {
          path: 'home',
          component: import17.HomeComponent
        }
        ,
        {
          path: 'events',
          component: import18.EventsComponent
        }
        ,
        {
          path: 'events/:event_key',
          component: import19.EventComponent
        }
        ,
        {
          path: '',
          redirectTo: '/',
          pathMatch: 'full'
        }
        ,
        {
          path: '**',
          component: import17.HomeComponent
        }

      ]
    ];
    this._Router_26 = import4.ɵe(this._ApplicationRef_10,this._UrlSerializer_18,this._RouterOutletMap_19,this._Location_22,this,this._NgModuleFactoryLoader_24,this._Compiler_23,this._ROUTES_25,this._ROUTER_CONFIGURATION_20,this.parent.get(import4.UrlHandlingStrategy,(null as any)),this.parent.get(import4.RouteReuseStrategy,(null as any)));
    this._RouterModule_27 = new import4.RouterModule(this._ɵa_17,this._Router_26);
    this._AppRoutingModule_28 = new import9.AppRoutingModule();
    this._AppModule_29 = new import10.AppModule();
    this._AppServerModule_30 = new import1.AppServerModule();
    return this._AppServerModule_30;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.CommonModule)) { return this._CommonModule_1; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_2; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_3; }
    if ((token === import4.ɵg)) { return this._ɵg_4; }
    if ((token === import0.APP_ID)) { return this._APP_ID_5; }
    if ((token === import5.ɵTRANSITION_ID)) { return this._ɵTRANSITION_ID_6; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_7; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_8; }
    if ((token === import0.ɵf)) { return this._ɵf_9; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_10; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_11; }
    if ((token === import5.BrowserModule)) { return this._BrowserModule_12; }
    if ((token === import6.NoopAnimationsModule)) { return this._NoopAnimationsModule_13; }
    if ((token === import7.ServerModule)) { return this._ServerModule_14; }
    if ((token === import8.ɵba)) { return this._ɵba_15; }
    if ((token === import8.FormsModule)) { return this._FormsModule_16; }
    if ((token === import4.ɵa)) { return this._ɵa_17; }
    if ((token === import4.UrlSerializer)) { return this._UrlSerializer_18; }
    if ((token === import4.RouterOutletMap)) { return this._RouterOutletMap_19; }
    if ((token === import4.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_20; }
    if ((token === import3.LocationStrategy)) { return this._LocationStrategy_21; }
    if ((token === import3.Location)) { return this._Location_22; }
    if ((token === import0.Compiler)) { return this._Compiler_23; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_24; }
    if ((token === import4.ROUTES)) { return this._ROUTES_25; }
    if ((token === import4.Router)) { return this._Router_26; }
    if ((token === import4.RouterModule)) { return this._RouterModule_27; }
    if ((token === import9.AppRoutingModule)) { return this._AppRoutingModule_28; }
    if ((token === import10.AppModule)) { return this._AppModule_29; }
    if ((token === import1.AppServerModule)) { return this._AppServerModule_30; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_31; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_32; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_33; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_34; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_35; }
    if ((token === import2.Http)) { return this._Http_36; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_37; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_38; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_39; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_40; }
    if ((token === import5.DomSanitizer)) { return this._DomSanitizer_41; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_42; }
    if ((token === import5.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_43; }
    if ((token === import5.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_44; }
    if ((token === import5.EventManager)) { return this._EventManager_45; }
    if ((token === import5.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_46; }
    if ((token === import5.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_47; }
    if ((token === import7.ɵb)) { return this._ɵb_48; }
    if ((token === import5.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_49; }
    if ((token === import7.ɵServerRendererFactory2)) { return this._ɵServerRendererFactory2_50; }
    if ((token === import11.ɵAnimationEngine)) { return this._ɵAnimationEngine_51; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_52; }
    if ((token === import0.Testability)) { return this._Testability_53; }
    if ((token === import5.Meta)) { return this._Meta_54; }
    if ((token === import5.Title)) { return this._Title_55; }
    if ((token === import8.ɵi)) { return this._ɵi_56; }
    if ((token === import4.ActivatedRoute)) { return this._ActivatedRoute_57; }
    if ((token === import4.NoPreloading)) { return this._NoPreloading_58; }
    if ((token === import4.PreloadingStrategy)) { return this._PreloadingStrategy_59; }
    if ((token === import4.RouterPreloader)) { return this._RouterPreloader_60; }
    if ((token === import4.PreloadAllModules)) { return this._PreloadAllModules_61; }
    if ((token === import4.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_62; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_63; }
    if ((token === import12.FTCDatabase)) { return this._FTCDatabase_64; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_9.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_46 && this._ɵDomSharedStylesHost_46.ngOnDestroy());
    (this.__RouterPreloader_60 && this._RouterPreloader_60.ngOnDestroy());
  }
}
export const AppServerModuleNgFactory:import0.NgModuleFactory<import1.AppServerModule> = new import0.NgModuleFactory<any>(AppServerModuleInjector,import1.AppServerModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiWjovQ29kaW5nL1JlcG9zaXRvcmllcy9UaGVZZWxsb3dBbGxpYW5jZS9zcmMvYXBwL2FwcC5zZXJ2ZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1o6L0NvZGluZy9SZXBvc2l0b3JpZXMvVGhlWWVsbG93QWxsaWFuY2Uvc3JjL2FwcC9hcHAuc2VydmVyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
